In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
class Forward_Kinematics:
    def __init__(self,joints):
        self.j = joints
    
    def homo_Mat(self,dh_par):
        return np.array([[np.cos(np.deg2rad(dh_par[3])),-np.sin(np.deg2rad(dh_par[3]))*np.cos(np.deg2rad(dh_par[1])),np.sin(np.deg2rad(dh_par[3]))*np.sin(np.deg2rad(dh_par[1])),dh_par[0]*np.cos(np.deg2rad(dh_par[3]))],
                        [np.sin(np.deg2rad(dh_par[3])),np.cos(np.deg2rad(dh_par[3]))*np.cos(np.deg2rad(dh_par[1])),-np.cos(np.deg2rad(dh_par[3]))*np.sin(np.deg2rad(dh_par[1])),dh_par[0]*np.sin(np.deg2rad(dh_par[3]))],
                        [0,np.sin(np.deg2rad(dh_par[1])),np.cos(np.deg2rad(dh_par[1])),(dh_par[2])],
                        [0,0,0,1]])
    """
    def rotateX(self,theta):
        return np.array([[1,0,0,0],[0,np.cos(np.deg2rad(theta)),-np.sin(np.deg2rad(theta)),0],[0,np.sin(np.deg2rad(theta)),np.cos(np.deg2rad(theta)),0],[0,0,0,1]])
    
    def rotateZ(self,theta):
        return np.array([[np.cos(np.deg2rad(theta)),-np.sin(np.deg2rad(theta)),0,0],[np.sin(np.deg2rad(theta)),np.cos(np.deg2rad(theta)),0,0],[0,0,1,0],[0,0,0,1]])
    
    def TransX(self,val):
        mat = np.identity(4)
        mat[0][3]=val
        return mat
    
    def TransZ(self,val):
        mat = np.identity(4)
        mat[2][3]=val
        return mat
    
    def homoMat(self):
        dh_par = self.DH_Parameters()
        return np.matmul(np.matmul(self.TransZ(dh_par[2]),self.rotateZ(dh_par[3])),np.matmul(self.TransX(dh_par[0]),self.rotateX(dh_par[1])))
    """
    """The above functions can be used as a replacement for below homo_Mat function """
        
    def finPos(self,mat):
        print(f"DH Parameters: \n {mat}" )
        finHomo = np.identity(4)
        homo_mat = np.zeros((4,4))
        for i in range(self.j):
            homo_mat = self.homo_Mat(mat[i,:]) # ----> Call this for homo_Mat
            finHomo = np.matmul(finHomo,homo_mat)
        
        return np.round(finHomo,3)

## For ABB_IRB_1410 

In [23]:
IRB_1410 = np.array([[0, 90, 475, 30],[150, 0, 0, 60],[600, 90, 0, 60] ,[120, -90, 720, 30],[0, 90, 0, 90],[0, 0, 85, 60]])

In [28]:
total_joints = 6
if -170<=IRB_1410[0][3]<=170 and  -70<=IRB_1410[1][3]<=70 and -65<=IRB_1410[2][3]<=65 and -150<=IRB_1410[3][3]<=150 and -115<=IRB_1410[4][3]<=115 and -300<=IRB_1410[5][3]<=300:
    model2 = Forward_Kinematics(total_joints)

In [29]:
model2.finPos(IRB_1410)

DH Parameters: 
 [[  0  90 475  30]
 [150   0   0  60]
 [600  90   0  60]
 [120 -90 720  30]
 [  0  90   0  90]
 [  0   0  85  60]]


array([[ 1.870000e-01,  9.740000e-01, -1.250000e-01,  3.195190e+02],
       [-7.580000e-01,  6.200000e-02, -6.500000e-01,  6.611800e+01],
       [-6.250000e-01,  2.170000e-01,  7.500000e-01,  1.638269e+03],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

## Generic Case

In [ ]:
total_joints = int(input("Enter total number of joints in Manipulator: "))
model3 = Forward_Kinematics(total_joints)

Enter total number of joints in Manipulator:  6


In [ ]:
DH_params = np.zeros((total_joints,4))
for i in range(total_joints):
    print(f"Enter DH Parameters for Joint {i}:")
    for j in range(4):
        DH_params[i][j] = float(input())
        
print("Dh Parameters for Model: \n",DH_params)

Enter DH Parameters for Joint 0:


 180
 90
 400
 0


Enter DH Parameters for Joint 1:


 600
 180
 135
 0


Enter DH Parameters for Joint 2:


 120
 -90
 135
 0


Enter DH Parameters for Joint 3:


 0
 90
 620
 0


Enter DH Parameters for Joint 4:


 0
 -90
 0
 0


Enter DH Parameters for Joint 5:


 0
 0
 115
 0


Dh Parameters for Model: 
 [[180.  90. 400.   0.]
 [600. 180. 135.   0.]
 [120. -90. 135.   0.]
 [  0.  90. 620.   0.]
 [  0. -90.   0.   0.]
 [  0.   0. 115.   0.]]


In [ ]:
model3.finPos(DH_params) #taken for KUKA KR -5 from SK Saha's Book: Page 172

DH Parameters: 
 [[180.  90. 400.   0.]
 [600. 180. 135.   0.]
 [120. -90. 135.   0.]
 [  0.  90. 620.   0.]
 [  0. -90.   0.   0.]
 [  0.   0. 115.   0.]]


array([[   1.,    0.,    0.,  900.],
       [   0.,   -1.,   -0.,   -0.],
       [   0.,    0.,   -1., -335.],
       [   0.,    0.,    0.,    1.]])